# 1-bosqich: React build
FROM node:20-alpine AS builder
WORKDIR /app
COPY webapp/package*.json ./
RUN npm ci
COPY webapp/ .
RUN npm run build

# 2-bosqich: Nginx bilan serve qilish
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY webapp/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
